spring.datasource:
  driver-class-name: org.mariadb.jdbc.Driver
spring.jpa:
  hibernate.ddl-auto: validate
  properties.hibernate:
    show_sql: true
    format_sql: true
    query.substitutions: true
    dialect: org.hibernate.dialect.MariaDBDialect