spring.datasource:
  url: jdbc:mariadb://localhost:3306/friendface
  username: root
  driver-class-name: org.mariadb.jdbc.Driver
  password: 'Init5!?!Init5!?!'
spring.jpa:
  hibernate.ddl-auto: validate
  properties.hibernate:
    show_sql: true
    format_sql: true
    query.substitutions: true